apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerakswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerakswebapp
  template:
    metadata:
      labels:
        app: dockerakswebapp
    spec:
      containers:
        - name: dockerakswebapp
          image: acrdelete.azurecr.io/akswebappimg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          # Optional but recommended — add probes  
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
