apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerakswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerakswebapp
  template:
    metadata:
      labels:
        app: dockerakswebapp
    spec:
      containers:
      - name: dockerakswebapp
        image: containerregisteryrgelete.azurecr.io/dockerakswebapp:latest
        ports:
        - containerPort: 80