apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerakswebapp
  labels:
    app: dockerakswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerakswebapp
  template:
    metadata:
      labels:
        app: dockerakswebapp
    spec:
      containers:
        - name: dockerakswebapp
          image: acrdelete.azurecr.io/akswebappimg:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-pull-secret
