apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dockerakswebapp-ingress
  annotations:
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com
spec:
  rules:
    - host: dockerakswebapp.centralindia.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dockerakswebapp-svc
                port:
                  number: 8080
