apiVersion: v1
kind: Service
metadata:
  name: dockerapp-svc
  labels:
    app: dockerapp
spec:
  type: LoadBalancer
  selector:
    app: dockerapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
