apiVersion: v1
kind: Service
metadata:
  name: dockerapp-svc
  labels:
    app: dockerakswebapp
spec:
  type: LoadBalancer
  selector:
    app: dockerakswebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
