name: Build and Deploy Docker .NET App to Azure App Service,AKS
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: acrdelete.azurecr.io
  IMAGE_NAME: akswebappimg
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # -------------------------------------------------------
      # MULTI-ARCH BUILD & PUSH (REPLACES YOUR OLD BUILD STEPS)
      # -------------------------------------------------------
      - name: Build and Push multiarch image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG \
            -f DockerAKSWebApp/Dockerfile DockerAKSWebApp \
            --push

      - name: Install kubelogin
        run: |
          curl -LO https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          sudo mv bin/linux_amd64/kubelogin /usr/local/bin/kubelogin
          sudo chmod +x /usr/local/bin/kubelogin

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Update kubeconfig for kubelogin
        run: |
          kubelogin convert-kubeconfig -l azurecli

      - name: Deploy to AKS
        run: |
          kubectl apply -f DockerAKSWebApp/k8s/deployment.yaml
          kubectl apply -f DockerAKSWebApp/k8s/service.yaml
          kubectl apply -f DockerAKSWebApp/k8s/ingress.yaml
          kubectl rollout status deployment/dockerakswebapp
